version: 2
updates:
  # Python dependencies via pip
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "06:00"
      timezone: "Asia/Jakarta"
    reviewers:
      - "yantology"
    assignees:
      - "yantology"
    commit-message:
      prefix: "deps"
      prefix-development: "deps-dev"
      include: "scope"
    open-pull-requests-limit: 5
    target-branch: "main"
    labels:
      - "dependencies"
      - "automated"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "07:00"
      timezone: "Asia/Jakarta"
    reviewers:
      - "yantology"
    assignees:
      - "yantology"
    commit-message:
      prefix: "ci"
      include: "scope"
    open-pull-requests-limit: 3
    labels:
      - "github-actions"
      - "automated"
