name: Documentation
description: Report missing, unclear, or incorrect documentation
title: "[Docs]: "
labels: ["documentation", "needs-triage"]

body:
  - type: markdown
    attributes:
      value: |
        Thanks for helping us improve our documentation!

  - type: input
    id: contact
    attributes:
      label: Contact Details
      description: How can we get in touch with you if we need more info?
      placeholder: ex. email@example.com
    validations:
      required: false

  - type: dropdown
    id: doc-type
    attributes:
      label: Documentation Type
      description: What type of documentation issue is this?
      options:
        - Missing documentation
        - Incorrect/outdated documentation
        - Unclear/confusing documentation
        - Typo/grammar issue
        - Code example issue
        - API documentation
        - Installation guide
        - Tutorial/guide
        - Other
    validations:
      required: true

  - type: textarea
    id: location
    attributes:
      label: Documentation Location
      description: Where is the documentation issue located?
      placeholder: |
        - URL: https://...
        - File: docs/...
        - Section: Getting Started
        - Page: Installation Guide
    validations:
      required: true

  - type: textarea
    id: current-content
    attributes:
      label: Current Content
      description: What does the current documentation say? (if applicable)
      placeholder: Copy and paste the current content here
    validations:
      required: false

  - type: textarea
    id: issue-description
    attributes:
      label: Issue Description
      description: Describe what's wrong or missing
      placeholder: The documentation is unclear because...
    validations:
      required: true

  - type: textarea
    id: suggested-improvement
    attributes:
      label: Suggested Improvement
      description: How would you improve the documentation?
      placeholder: |
        The documentation should explain...
        Add an example showing...
        Clarify the section about...
    validations:
      required: true

  - type: dropdown
    id: audience
    attributes:
      label: Target Audience
      description: Who is the primary audience for this documentation?
      options:
        - Beginners
        - Intermediate users
        - Advanced users
        - Developers
        - All users
    validations:
      required: true

  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context
      description: Add any other context, screenshots, or examples
    validations:
      required: false

  - type: checkboxes
    id: research
    attributes:
      label: Research
      description: Please confirm you have done the following
      options:
        - label: I have searched existing issues to make sure this hasn't been reported before
          required: true
        - label: I have checked if this documentation exists elsewhere
          required: true

  - type: checkboxes
    id: terms
    attributes:
      label: Code of Conduct
      description: By submitting this issue, you agree to follow our Code of Conduct
      options:
        - label: I agree to follow this project's Code of Conduct
          required: true