name: Publish to PyPI

on:
  release:
    types: [published]
  workflow_dispatch: # Keep manual trigger
    inputs:
      test_pypi:
        description: 'Publish to Test PyPI instead of PyPI'
        required: false
        default: false
        type: boolean

jobs:
  build:
    name: Build Distribution
    runs-on: ubuntu-latest
    outputs:
      # True if release event with valid tag
      should_publish_release: ${{ github.event_name == 'release' && startsWith(github.event.release.tag_name, 'v') }}
      # Actual tag name from release
      tag_name: ${{ github.event.release.tag_name }}

    steps:
    - name: Check if release is a candidate for publishing
      id: trigger_check
      run: |
        is_valid='false'
        if [[ "${{ github.event_name }}" == "release" && \
              "${{ github.event.action }}" == "published" && \
              "${{ github.event.release.tag_name }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          is_valid='true'
          echo "Release is a candidate for publishing."
          echo "Tag name: ${{ github.event.release.tag_name }}"
        else
          echo "Release is NOT a candidate for publishing."
          echo "Event name: ${{ github.event_name }}"
          echo "Action: ${{ github.event.action }}"
          echo "Tag name: ${{ github.event.release.tag_name }}"
        fi
        echo "is_valid_release_for_publish=$is_valid" >> $GITHUB_OUTPUT

    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # For release events, checkout the tag; for workflow_dispatch, use current ref
        ref: ${{ github.event_name == 'release' && github.event.release.tag_name || github.ref }}
        fetch-depth: 0

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'

    - name: Install UV
      uses: astral-sh/setup-uv@v3

    - name: Install dependencies
      run: uv sync --dev

    - name: Build package
      run: uv build

    - name: Check distribution
      run: |
        uv add --dev twine
        uv run twine check dist/*

    - name: Validate tag format
      id: tag_info
      if: github.event_name == 'release'
      run: |
        TAG_NAME="${{ github.event.release.tag_name }}"
        if [[ "$TAG_NAME" =~ ^v[0-9]+\.[0-9]+\.[0-9]+$ ]]; then
          echo "Valid publishable tag: $TAG_NAME"
          echo "tag_exists=true" >> $GITHUB_OUTPUT
          echo "tag_name=$TAG_NAME" >> $GITHUB_OUTPUT
        else
          echo "Invalid tag format: $TAG_NAME (expected vX.Y.Z)"
          echo "tag_exists=false" >> $GITHUB_OUTPUT
          echo "tag_name=" >> $GITHUB_OUTPUT
        fi

    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: python-package-distributions
        path: dist/
        if-no-files-found: error

  publish-to-pypi:
    name: Publish to PyPI
    if: >
      (github.event_name == 'release' && needs.build.outputs.should_publish_release == 'true') ||
      (github.event_name == 'workflow_dispatch' && !inputs.test_pypi)
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/generatecv
    permissions:
      id-token: write # Required for trusted PyPI publishing

    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish to PyPI
      if: needs.build.outputs.tag_name != '' || github.event_name == 'workflow_dispatch' # Ensure tag exists for release
      uses: pypa/gh-action-pypi-publish@release/v1
      # For release events, pypa/gh-action-pypi-publish will use the tag from needs.build.outputs.tag_name
      # if it's set and matches the version in the package.
      # For workflow_dispatch, it will publish based on the built package version.

  publish-to-testpypi:
    name: Publish to TestPyPI
    if: github.event_name == 'workflow_dispatch' && inputs.test_pypi
    needs: build
    runs-on: ubuntu-latest
    environment:
      name: testpypi
      url: https://test.pypi.org/p/generatecv
    permissions:
      id-token: write # Required for trusted PyPI publishing

    steps:
    - name: Download distributions
      uses: actions/download-artifact@v4
      with:
        name: python-package-distributions
        path: dist/

    - name: Publish to TestPyPI
      uses: pypa/gh-action-pypi-publish@release/v1
      with:
        repository-url: https://test.pypi.org/legacy/
        # For workflow_dispatch, it will publish based on the built package version.