name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.13
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install -e .[dev]
        # Explicitly install required dependencies that might be missing
        python -m pip install email-validator types-setuptools types-reportlab
        # Make sure dependencies are actually installed
        python -c "import email_validator; print('Email validator found')"
    
    - name: Lint with Ruff
      run: |
        ruff check .
    
    - name: Check formatting with Black
      run: |
        black --check .
    
    - name: Type check with mypy
      run: |
        mypy .
    
    - name: Test with pytest and coverage
      run: |
        # Set the PYTHONPATH to include the current directory
        PYTHONPATH=$PYTHONPATH:$(pwd) pytest --cov=generatecv --cov-report=xml
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v3
      with:
        file: ./coverage.xml
        fail_ci_if_error: false