name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  test:
    name: Test Python ${{ matrix.python-version }} on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
        python-version: ['3.13']
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
      with:
        enable-cache: true
        cache-dependency-glob: "uv.lock"
    
    - name: Install dependencies
      run: |
        uv sync --dev
        uv run python -c "import email_validator; print('Email validator found')"
    
    - name: Lint with Ruff
      run: |
        uv run ruff check .
    
    - name: Check formatting with Black
      run: |
        uv run black --check .
    
    - name: Type check with pyrefly
      run: |
        uv run pyrefly check
    
    - name: Test with pytest and coverage
      run: |
        uv run pytest --cov=generatecv --cov-report=xml --cov-report=term-missing
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: matrix.os == 'ubuntu-latest'
      with:
        file: ./coverage.xml
        fail_ci_if_error: false
        token: ${{ secrets.CODECOV_TOKEN }}

  build-test:
    name: Build and Test Package
    runs-on: ubuntu-latest
    needs: test
    
    steps:
    - uses: actions/checkout@v5
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Install UV
      uses: astral-sh/setup-uv@v3
    
    - name: Build package
      run: |
        uv build
    
    - name: Check package metadata
      run: |
        uv add --dev twine
        uv run twine check dist/*
    
    - name: Test package installation
      run: |
        python -m pip install dist/*.whl
        generatecv-example --help || echo "CLI script test completed"
    
    - name: Upload build artifacts
      uses: actions/upload-artifact@v4
      with:
        name: dist-${{ github.run_id }}
        path: dist/
        retention-days: 7

  auto-tag:
    name: Auto Tag Release
    runs-on: ubuntu-latest
    needs: [test, build-test]
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write
    
    steps:
    - uses: actions/checkout@v5
      with:
        fetch-depth: 0
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.13'
    
    - name: Extract version from pyproject.toml
      id: get_version
      run: |
        VERSION=$(python -c "import tomllib; f=open('pyproject.toml', 'rb'); data=tomllib.load(f); print(data['project']['version'])")
        echo "version=$VERSION" >> $GITHUB_OUTPUT
        echo "Current version: $VERSION"
    
    - name: Get latest tag
      id: get_latest_tag
      run: |
        set +e
        LATEST_TAG=$(git tag -l --sort=-version:refname | grep -E '^v?[0-9]+\.[0-9]+\.[0-9]+' | head -n1)
        set -e
        
        if [ -z "$LATEST_TAG" ]; then
          LATEST_TAG="0.0.0"
          echo "No existing tags found, using default: $LATEST_TAG"
        else
          echo "Found latest tag: $LATEST_TAG"
        fi
        
        echo "latest_tag=$LATEST_TAG" >> $GITHUB_OUTPUT
    
    - name: Compare versions
      id: compare_versions
      run: |
        CURRENT_VERSION=${{ steps.get_version.outputs.version }}
        LATEST_TAG=${{ steps.get_latest_tag.outputs.latest_tag }}
        
        python << EOF
        def version_tuple(v):
            if not v or v.strip() == "":
                return (0, 0, 0)
            v = v.lstrip('v')
            parts = v.split(".")
            while len(parts) < 3:
                parts.append("0")
            try:
                return tuple(int(part) for part in parts[:3])
            except ValueError:
                return (0, 0, 0)
        
        current = version_tuple("$CURRENT_VERSION")
        latest = version_tuple("$LATEST_TAG")
        
        print(f"Current version tuple: {current}")
        print(f"Latest version tuple: {latest}")
        
        if current > latest:
            print("Version is newer")
            exit(0)
        elif current == latest:
            print("Version is the same")
            exit(1)
        else:
            print("Version is older")
            exit(2)
        EOF
        
        if [ $? -eq 0 ]; then
          echo "should_tag=true" >> $GITHUB_OUTPUT
          echo "✅ Version $CURRENT_VERSION is newer than $LATEST_TAG"
        elif [ $? -eq 1 ]; then
          echo "should_tag=false" >> $GITHUB_OUTPUT
          echo "⚠️  Version $CURRENT_VERSION is the same as $LATEST_TAG - skipping tag creation"
        else
          echo "should_tag=false" >> $GITHUB_OUTPUT
          echo "❌ Version $CURRENT_VERSION is older than $LATEST_TAG - skipping tag creation"
        fi
    
    - name: Create and push tag
      if: steps.compare_versions.outputs.should_tag == 'true'
      run: |
        VERSION=${{ steps.get_version.outputs.version }}
        git config user.name "github-actions[bot]"
        git config user.email "github-actions[bot]@users.noreply.github.com"
        git tag -a "v$VERSION" -m "Release version $VERSION"
        git push origin "v$VERSION"
        echo "🏷️  Created and pushed tag v$VERSION"
    
    - name: Create GitHub Release
      if: steps.compare_versions.outputs.should_tag == 'true'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ steps.get_version.outputs.version }}
        name: Release v${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        generate_release_notes: true